### ISSUE TITLE
Support non-JS file extensions

### ISSUE THREAD

**Issue by letmaik** [mbostock/rollup-plugin-ascii#2]
The plugin should support other file extensions as well, like `.ts`.

**Comment by mbostock** [comment]
This plugin currently uses Acorn to parse JavaScript modules, so I don’t think it would work if you tried to point it at TypeScript. (It needs to parse JavaScript because it only escapes non-ASCII characters in string literals; it doesn’t look at the rest of the code.)

But, if you or someone else wants to take a crack at generalizing it to other languages or JavaScript dialects, have at it and send me a PR, or feel free to fork this plugin and release your own.
